config/routes.rb
Yc::Application.routes.draw do
  resources :jobs
  match "add_job/:id" => "jobs#add_job", :as => "add_job", :via => :put

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  root :to => "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Abilities
    # :manage
    # :create
    # :read
    # :update
    # :destroy

    # :manage, :all
    # :manage, Model


    if user.super_admin?
      can :manage, :all
    elsif user.admin?
      can :manage, :all
    else # default role for newly created account, "visitor"
      can :read, Job
      can [:read, :update], User, :id => user.id
    end
  end
end

app/models/admin_user.rb
# encoding: UTF-8
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :job
  belongs_to :user
end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :applications
  has_many :users, :through => :applications
  belongs_to :job_category
end

app/models/job_category.rb
class JobCategory < ActiveRecord::Base
  has_many :jobs
end

app/models/user.rb
# encoding: UTF-8
class User < ActiveRecord::Base
  has_many :applications
  has_many :jobs, :through => :applications
  has_many :job_categories
  
  devise :database_authenticatable, :registerable, :recoverable, :trackable, :validatable

  attr_accessible :email, :password, 
    :password_confirmation, 
    :remember_me, 
    :fname, 
    :lname, 
    :bday, 
    :address, 
    :areacode, 
    :city, 
    :education, 
    :info, 
    :looking_for, 
    :tele,
    :cv,
    :cv_file_name, 
    :cv_content_type,
    :cv_file_size,
    :cv_updated_at,
    :role

  has_attached_file :cv

  validates_attachment_size :cv, :less_than => 2.megabytes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/jobs_controller.rb
# encoding: UTF-8
class JobsController < InheritedResources::Base
  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @jobs = Job.order("updated_at DESC").all
  end

  def add_job
    @job = Job.find(params[:id])
    current_user.jobs << @job
    redirect_to jobs_path, :notice => "Du har nu sökt jobbet: #{@job.name}."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/admin/jobs/_users.html.erb
<h2>Users:</h2>
<% @job.users.each do |user| %>
  <%= link_to user.fname + " " + user.lname, admin_user_path(user) %>

  <br />
<% end %>

app/views/admin/users/_extra.html.erb
<h2>CV:</h2>
<%= link_to user.cv_file_name, "#{root_path}system/cvs/#{user.id}/original/#{user.cv_file_name}" %>

<br />
<br />
<h2>Jobs:</h2>
<% @user.jobs.each do |job| %>

  <%= link_to job.name, job %>
  <br />

<% end %>

app/views/home/index.html.erb
<h2>Information</h2>
<p>För att kunna söka jobb, så måste du registrera dig och logga in först.<br />
<h2>Sök jobb</h2>
<p>Genom Young Consulting kan du arbeta som uthyrd konsult eller bli rekryterad till en tjänst direkt hos någon av våra uppdragsgivare.</p>
<p>
Att jobba som konsult kan vara ett sätt att snabbstarta karriären. Vi har många attraktiva företag som kunder och kan därför erbjuda kvalificerade och roliga konsultuppdrag inom många olika områden och branscher. Du får en chans att skapa viktiga kontakter och utveckla din kompetens.
Vi erbjuder både heltidsjobb och deltidsjobb beroende på vad som passar dig bäst.
</p>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h2>Lediga jobb</h2>
<table width="700">
	<tr align="left">
		<th>Datum </th>
		<th>Arbetsbeskrivning</th>
		<th>Ort</th>
    <th></th>
	</tr>
	<% @jobs.each do |job| %>
    <tr>
      <td><%= job.updated_at.strftime("%d/%m/%Y") %></td>
      <td><%= link_to job.name, job %></td>
      <td>Stockholm</td>
      <td>
        <% if current_user %>
          <% if job.users.exists?(current_user) %>
            <span style="color:green;">Du har sökt jobbet</span>
          <% else %>
            <%= link_to("Sök jobb", add_job_path(job.id), :method => :put) %>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<br />

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>
  <h2><%= @job.name %></h2>
<%= @job.updated_at.strftime("%d/%m/%Y") %>

<br />

<%= @job.title %>

<br /><br />

<%= raw @job.content %>

<br /><br />
<% if current_user %>
  <% if @job.users.exists?(current_user) %>
    <span style="color:green;">Du har sökt jobbet</span>
  <% else %>
    <%= link_to("Sök jobbet", add_job_path(@job.id), :method => :put) %>
  <% end %>
<% else %>
  <p>Du måste vara <%= link_to "registrerad", new_user_registration_path %> och <%= link_to "inloggad", new_user_session_path %> för att kunna ansöka.</p>
<% end %>

<br />
<br />
<%= link_to 'Tillbaka', jobs_path %>

app/views/layouts/application.html.erb
<% # encoding: UTF-8 %>
<!DOCTYPE html>
<html>
<head>
  
  <title>
    <% if user_signed_in? %>
      YoungConsulting.se | Inloggad <%= current_user.fname.capitalize %>
    <% else %>
      YoungConsulting.se
    <% end %>
 </title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  
  <div id="logo">
  </div>

		<div id="menu">
			<ul>
				<li class="active"><%= link_to "Startsidan", 'http://youngconsulting.se' %></li>
				<li><%= link_to "Lediga jobb", jobs_path %></li>
			<% if user_signed_in? %>
				<li><%= link_to "Min Profil", edit_user_registration_path %></li>		
				<li><%= link_to "Logga ut", destroy_user_session_path, :method => :delete %></li>
			<% else %>
				<li><%= link_to "Logga in", new_user_session_path %></li>
				<li><%= link_to "Registrera", new_user_registration_path %></li>
			<% end %>	
			</ul>
		</div>

  <div class="text">
		<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>

</div>
</body>
</html>